blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/mlorentedev/boilerplates/tree/main/docs
    about: Check the documentation for help and guides
  - name: Discussions
    url: https://github.com/mlorentedev/boilerplates/discussions
    about: Ask questions and discuss ideas
